const enAU = {
// app 
		LaunchingApp: 'Launching app',
		ServerCannotLoadSystemConfig: 'Cannot load system configuration, please check your internet and try again later',
		NeedToUpdateTitle: 'Your app needs to be updated',
		NeedToUpdateMessage: 'The version of your app is too low, please update.',
		GoToAppStore: 'Take me to App Store',
		GoToAppStoreMessage: 'You can go to app store and download the latest version of the app.',		
		CheckingUpdate: 'Checking Updates',
		IsNewestVersion: 'Congratz',
		IsNewestVersionMessage: 'Your app is already the newest version',
		HasNewerVersion: 'Update is available',
		ServerNotAbleToInit: 'Not able to initialize the app, please check you network and try again.',
		CantOpenDeepLink: "Can't open deep link.",
		CurrentVersion: 'Current Version',
		ChangeLanguage: 'Change Language',
		FromFunnyThings: 'from Funny Things App ...',
// common
		Back: "Back",
		Cancel: 'Cancel',
		Retry: 'Retry',
		OK: 'OK',
		Thousand: 'K',
		Million: 'M',
		Billion: 'B',
		Copy: 'Copy',
		Submit: 'Submit',
		Download: 'Download',
		Comment: 'Comment',
		FeatureCommingSoon: 'This feature is comming soon. "Just joking" is my solo project, please be patient and allow some time for me to complete all the missing features.',
		Error: 'Error',
		LoadingUploadingImages: 'Uploading images, this might take a white, please be patient.',
		LoadingCompressingImages: 'Compressing images',
		LoadingSigningUp: 'Signing Up',
		LoadingSigningIn: 'Signing In',
		LoadingSigningOut: 'Signing Out',
		LoadingUpdatingProfile: 'Updating Profile',
		LoadingUploadingPost: 'Uploading Post',
// Auth
		SignIn: 'Sign In',
		SignUp: 'Sign Up',
		SignOut: 'Sign Out',
		Policy: 'Policy',
		ContinueWith: 'Continue With ...',
		ForgotPassword: 'Forgot Password ?',
		EnterEmail: 'Your E-mail Address ...',
		EnterPassword: 'Your Password ...',
		AgreeWithPolicy: 'By using this app, you agree with our policy',
		EmailEmpty: "Dont't forget your e-mail address",
		PasswordEmpty: 'Seems you forgot to enter a password',
		EmailInvalid: "Uhm, This e-mail doesn't look right.",
		EnterName: 'Enter name or nick name ...',
		NameEmpty: 'Please give us a name, any name will do',
		InvalidNameLength: 'Name must be 2 - 20 characters long',
		ConfirmPassword: 'Retype your password again ...',
		ConfirmPasswordEmpty: 'Please retype password here.',
		PasswordNotMatch: 'Two passwords entered does not match, please retype again.',
		PasswordInvalid: 'password needs to contain at least one ahpabetic character, one number and no special characters. The password length must be at least 8 characters long',
		ServerSignUpSuccess: 'Sign Up Success',
		ServerSignInSuccess: 'Sign In Success',
		ServerEmailInvalid: 'Email is inValid',
		ServerUserDisabled: 'Oops, your account is disabled, contact us for more info',
		ServerEmailExist: 'This email address already exists choose another one',
		ServerWrongEmailOrPassword: 'Your e-mail or passsword is wrong, please check',
		ServerDatabaseError: 'Databasee Error Occured',
		ServerGoogleConfigureFailed: 'Google Signin Configuration failed',
		ServerGoogleSigninFailed: 'Google Signin Failed',
		ServerUserCancelledLogin: 'User has cancelled login.',
		ServerObtainTokenError: 'Not able to obtain user token',
		ServerSignOutError: 'Contact server failed, but you local sign-in status is removed.',
//Home 
		Home: 'Home',
		Followed: 'Followed',
		Hot: 'Funny Things',
		Image: 'Image',
		Text: 'Text',
		PostEmpty: 'Oops, no funny things here at the moment, join us and share your funny things',
		LeaveComment: 'say something here ...',
		CommentTooShort: 'uhm, your comment is too short, wanna add anything more?',
		ServerNoMorePost: 'No more new post',
		ServerNoMoreComment: 'No more new comment',
		ServerListLoaded: 'New posts has been loaded.',
		ServerCommentLoaded: 'New comment has been loaded.',
		ServerNotAbleToUpdatePost: 'Not able to update post',
		ServerAddCommentSuccess: 'Your comment has been added',
		ServerAddCommentFail: 'Adding comment failed',
		LoadMore: 'Press to Load More',
// Image Tile List
		LongImage: 'click to see more ...',
		ImageHasBeenSaved: 'Image has been saved',
		ImageSavingFailed: 'Failed to save image',
		PostYourComment: "be the first one comment on this",
		NoImageSource: "No Image Source",
// Search
		Search: 'Search',
		TypeHere: 'Type here ...',
// Post 
		Post: 'Post',
		PostSomethingFunny: 'Post something funny and make people laugh.',
		Upload: 'Upload',
		Reset: 'Reset',
		ImageLimitReached: 'You can only select at most 1 images',
		ErrorEmptyContent: 'You cannot submit an empty content',
		ErrorTextLengthInvalid: 'A text post should be at least 30 and at most 300 characters long, please make sure you are actually telling a joke',
		ErrorTextTooLong: 'Please make sure it is less that 300 characters',
		ErrorSelectingImage: 'Error ocurred while selecting images',
		ClickToRemoveImage: 'Click image to remove it from the list',
		ErrorAddPost: 'Adding post failed',
		AddPostSuccess: 'Your joke has been added successfully',
		ServerPostDoesNotExist: 'This joke does not exist, it must have been removed',
		ImageTypeInvalid: 'Only png, jpeg, jpg and gif types of image are supported, invalid types are ingnored automatically',
		MaxGifLimit: 'Gif image file must not be larger that 2.5MB, larger size image are ignored',
		LoadGifError: 'Unable to load this gif',
// Inbox
		Inbox: 'Inbox',
// Profile
		Profile: 'Profile',
		Share: 'Share',
		Followers: 'Followers',
		Following: 'Following',
		Post: 'Post',
		NoTagline: "He doesn't have anything to say...",
// Setting
		Setting: 'Setting',
		Avatar: 'Avatar',
		ChooseYourProfilePicture:'Choose your profile picture',
		UserName: 'User Name',
		AddTagline: 'Add you tagline here',
		Tagline: 'Tagline',
		WhoCanSendMeMessages: 'Who can send me messages ?',
		Anyone: 'Anyone',
		WhoIAmFollowing: 'Who I am following',
		AutoPlayGif:'Autoplay GIF',
		AutoPlayVideos: 'Autoplay videos',
		MakeYourGeolocationPublic: 'Make you geolocation public',
		Help: 'Help',
		CleanCache: 'Clean Cache',
		ContactUs: 'Contact us',
		TermsAndConditions: 'Terms and Conditions',
		CheckAppUpdates: 'Check App Updates',
		UserNameRules: 'User Name must be 2-20 characters long, and not contain any special characters',
		TaglinePrompt: "Why don't start writing something funny here to let people remember you? Please make sure it is less that 100 characters",
		InvalidTaglineLength: 'Please make sure it is less that 100 characters',
		WordCount: 'word count:',
		ServerNameUpdateSuccess: 'Name has been updated',
		ServerTaglineUpdateSuccess: 'Tagline has been updated',		
		ServerPhotoUpdateSuccess: 'Photo has been updated',
		ErrorSelectingPicture: 'Error occured while selecting picture.',
		ErrorResizingImage: 'Error occured when resizing image',
		ServerFailToUploadFile: 'Fail to upload the file',
		ServerFileUploadSuccess: 'File has been uploaded successfully',
// others
		PermissionRequired: 'Permission required',
		PermissionWriteExternalStorageRequired: 'Please grant this app write permission to storage',
// language
		'en-AU':'English',
		'zh-TW':'繁体中文',
		'zh-CN':'简体中文',
	};

export default enAU;
